
## Authenticate user [/signup]
Authenticate one user to access protected routes.

### Create New User [POST]

::: note
#### <i class="fa fa-info"></i> Info
Once the user's authentication has been successfully, he/She must login with correct credentials
to obtain a JWT token sent in the `the response body`. This token will be used to
access protected routes.
:::

> The request's body is required and can't be null.

+ Request (application/json)

    + Body

            {
                "email": "dan70@gmail.com",
                "password": "toto"
            }

+ Response 200 (application/json)

   + Body

            {
                "success": "true",
                "message": "User created successfully",
                "user": {
                    "userId": "5e7c0a87e75d0f21c069c0a6",
                    "userEmail": "dan70@gmail.com",
                    "userPassword": "$2a$10$TuZKcEtFNyvWNWHuLyS5u.mCBiZ27aoMLA7IcccajrelV5QZsZ0F."
                }
            }

+ Response 400 (application/json)

    + Body

            {
                message: "All fields required"
            }

+ Response 409 (application/json)

    + Body

            {
                success: "false",
                message: "Mail already exists"
            }


+ Response 500 (application/json)

    + Body

            {
                message: "Server error"
            }





