# Group Questions
Group description (also with *Markdown*)

## Important Info
Descriptions may also contain sub-headings and **more Markdown**.

## Question List [/questions]
Question list description

+ Even
+ More
+ Markdown

### Get Questions [GET]

Get a list of questions.

+ Response 200 (application/json)

    + Headers

            X-Request-ID: f72fc914
            X-Response-Time: 4ms

    + Body

            <!-- include(get-all-questions-rep.json) -->
            
+ Response 404 (application/json)

    + Body

            {
                "message ": "No documents found in the database"
            }
            
+ Response 500 (application/json)

    + Body

            {
                "error ": "An error occured while trying to get data from the database"
            }

### Create New Question [POST]


You may create your own question using this action. It takes a JSON
object containing a question and a list of answers in the
form of choices and correct answer.

Create a new question using a question and it's answers content body.

> A body is required in the request sent to create a question



+ Request with a body (application/json)

    + Body

            <!-- include(post-questions-body.json) -->
            
+ Response 201

    + Body


            {
                "message": "Created question successfully"
            }


+ Response 405 (application/json)

    + Body

            {
                message : "Invalid input"
            }


+ Response 500 (application/json)

    + Body

            {
                message : "Server error"
            }
            

## Question [/questions/{questionId}]

Question description

+ Parameters

    + questionId: `5e6444e51167df04c81f43e4` (required, string) - The question ID

### Get Question [GET]

Get a single question.

+ Parameters

    + questionId: `5e6444e51167df04c81f43e4` (string)

+ Response 200 (application/json)

    + Headers

            X-Request-ID: f72fc914
            X-Response-Time: 4ms
   + Body

            <!-- include(get-one-question.json) -->


+ Response 404 (application/json)

    + Headers

            X-Request-ID: f72fc914
            X-Response-Time: 4ms

    + Body

            {
                message: "No valid entry found for provided ID"
            }
+ Response 500 (application/json)

    + Body

            {
                message : "Server error"
            }
### Update a Question [PATCH]

Update a single question by setting the question value in the body request.

::: warning
#### <i class="fa fa-warning"></i> Caution
If the value for `the request body` is `null` or `undefined`, then the corresponding
value is not modified on the server. However, if you send an empty string instead then
it will **permanently overwrite** the original value.
:::

+ Request (application/json)

    + Body

            <!-- include(post-questions-body.json) -->

+ Response 200 (application/json)

    + Headers

            X-Request-ID: f72fc914
            X-Response-Time: 4ms

    + Body

            {
                "message": "Question updated",
                "modifiedDocs": result.nModified,
                "request": {
                    "type": "GET",
                    "url": `http://localhost:5000/api/questions/${questionId}`
                }
            }

+ Response 400 (application/json)

    + Headers

            X-Request-ID: f72fc914
            X-Response-Time: 4ms

    + Body

            {
                "message": "Please read the API doc to see how to update a question"
            }


+ Response 404 (application/json)

    + Headers

            X-Request-ID: f72fc914
            X-Response-Time: 4ms

    + Body

            {
                "message": "No valid entry found for provided ID"
            }

+ Response 500 (application/json)

    + Headers

            X-Request-ID: f72fc914
            X-Response-Time: 4ms

    + Body

            {
                "message": "Server error"
            }

### Delete a Question [DELETE]
Delete a single note

+ Response 200 (application/json)

    + Headers

            X-Request-ID: f72fc914
            X-Response-Time: 4ms

    + Body

            {
                message: "Question deleted successfully"
            }

+ Response 404 (application/json)

    + Headers

            X-Request-ID: f72fc914
            X-Response-Time: 4ms

    + Body

            {
                message: "No valid entry found for provided ID"
            }

+ Response 500 (application/json)

    + Headers

            X-Request-ID: f72fc914
            X-Response-Time: 4ms

    + Body

            {
                "message": "Server error"
            }
